Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/rails*
    - spec/spec*
    - config/initializers/devise.rb
    - config/*
    - config/*/*
    - bin/*
    - app/*/application_*
    - app/*/user*
    - test/test_helper*
    - test/application*
    - Rakefile
    - Gemfile
